# -*- coding: utf-8 -*-
"""kMean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQER7UppNZg-4UZtdrr4s-y8sjdHA4gq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv(r'/content/Mall_Customers.csv')
df.head()

print(df.info())
print(df.describe())

plt.scatter(df['Annual Income (k$)'], df['Spending Score (1-100)'])
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Customer Distribution')
plt.show()

X = df[['Annual Income (k$)','Spending Score (1-100)']]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X

wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i, random_state=42)
  kmeans.fit(X_scaled)
  wcss.append(kmeans.inertia_)

print("WCSS values : ",wcss)

plt.plot(range(1,11),wcss,marker ='o')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.title('Elbow Method')
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)
df.head(10)

df

X_scaled

plt.figure(figsize=(8,6))
for cluster in range(5):
  plt.scatter(
      df[df['Cluster'] == cluster]['Annual Income (k$)'],
      df[df['Cluster'] == cluster]['Spending Score (1-100)'],
  )

  plt.xlabel('Annual Income (k$)')
  plt.ylabel('Spending Score (1-100)')
  plt.title('Customer Distribution')
  plt.legend()

import joblib

joblib.dump(scaler,"scaler.pkl")
joblib.dump(kmeans,"kmeans_model.pkl")

